### ISSUE TITLE
Just a query regarding this main.c file?

### ISSUE THREAD

**Issue by shiivamgupta** [GreyZhang/g_s32k144#1]
this code will run infinite time correct?
--------------------------------------------------------------------------------------------------
#define COUNTER_LIMIT 100

        int counter = 0;

        for(;;) {       
            counter++;

            if(counter > COUNTER_LIMIT) {
                counter = 0;
            }
        }
-------------------------------------------------------------------------------------------------------------
 why we need to put these below lines:- if defined(_ghs_) and what is GHS and IAR can you explain me in brief?
Many Thanks!
----------------------------------------------------------------------------------------------
   /* to avoid the warning message for GHS and IAR: statement is unreachable*/
#if defined (__ghs__)
#pragma ghs nowarning 111
#endif
#if defined (__ICCARM__)
#pragma diag_suppress=Pe111
#endif
	return 0;
}

**Comment by GreyZhang** [comment]
1. Yes.
  I think you should learn some basic C language first. Besides, you need to learn some debugging skills.
  You can do some test to get the answer:
  Design code like this:
  Compile and run:


You sould get something like this:




2. They are names of compilers, just google it.
    Why we design code like this: we can design just one copy code and it can work well both in these two compiler environments.







At 2020-04-06 16:43:57, "Shivam Gupta" <notifications@github.com> wrote:

this code will run infinite time correct?

#define COUNTER_LIMIT 100

    int counter = 0;

    for(;;) {       
        counter++;

        if(counter > COUNTER_LIMIT) {
            counter = 0;
        }
    }

why we need to put these below lines:- if defined(ghs) and what is GHS and IAR can you explain me in brief?
Many Thanks!

/* to avoid the warning message for GHS and IAR: statement is unreachable*/
#if defined (ghs)
#pragma ghs nowarning 111
#endif
#if defined (ICCARM)
#pragma diag_suppress=Pe111
#endif
return 0;
}

**Comment by shiivamgupta** [comment]
Many Thanks! Now i got it.
