### ISSUE TITLE
osif.h file not found?

### ISSUE THREAD

**Issue by shiivamgupta** [GreyZhang/g_s32k144#2]
Hello Sir, 
I was trying this S32K144_009_GPIO_LED code on my S32 Design Studio, I opened freertos_s32k144 from example, then i have replaced your generated code and sources folder but at the time of building the project, it is showing some error, could you guide us how can i use that project, what instructions should i follow.

**Comment by GreyZhang** [comment]
Check S32SDK_S32K144_UserManual.pdf document, chapter 16.99.
